# Local preview overrides for Windows.
# Use with: bundle exec jekyll serve --config _config.yml,_config_preview.yml

external_sources: []

imagemagick:
  enabled: false

exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - _posts/2023-07-04-jupyter-notebook.md
  - assets/jupyter/
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
